# Numpy

In [1]:
import numpy as np

In [3]:
a = np.array(range(10))

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(a)
# class로 구현됨

numpy.ndarray

In [8]:
l1 = [5, 4, 8, 10]
b = np.array(l1)
b

array([ 5,  4,  8, 10])

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

In [12]:
l2 = [1, 2.0, 3, 'a']
l2

[1, 2.0, 3, 'a']

In [15]:
np.array(l2)
# 숫자가 문자로 바뀌어서 들어간다.

array(['1', '2.0', '3', 'a'], dtype='<U32')

In [16]:
l3 = [1, 2.0, 3.0, 5.7]
c = np.array(l3)
c

array([1. , 2. , 3. , 5.7])

In [19]:
c.dtype
# floast 형

dtype('float64')

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b

array([ 5,  4,  8, 10])

In [22]:
c

array([1. , 2. , 3. , 5.7])

In [24]:
a.shape
# 개수 10개, 한개

(10,)

In [25]:
b.shape

(4,)

In [26]:
c.shape

(4,)

# 차원의 개념

In [28]:
l1 = [[1,2], [3,4]]
a = np.array(l1)
a

array([[1, 2],
       [3, 4]])

In [29]:
a.dtype

dtype('int32')

In [30]:
a.shape

(2, 2)

In [32]:
l2 = [[1,2,3], [3,4]]
b = np.array(l2)
b
# 차원의 개념이 적용되기 위헤서는 행, 열의 숫자가 같아야한다.

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [34]:
range(10)

range(0, 10)

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(2, 10, 2)
# range 와 사용이 똑같다.

array([2, 4, 6, 8])

In [44]:
np.linspace(10,20, 9)
# 10과 20사이의 구간을 9구간으로 균등하게 잘라서 가져온다.
# default 값은 50

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

# Shape

In [47]:
a = np.arange(2, 10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a.shape

(8,)

In [52]:
b = a.reshape(2, 4)
b
# 2행 4열로 만든다.
# 복사해서 새로 생긴다.

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [51]:
b.shape

(2, 4)

# Shape를 바꾸는 다른 방법

In [53]:
a.shape

(8,)

In [55]:
a.shape = (2,4)
a
# 직접 바꾸는 방법

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [58]:
a.shape = (-1)
a
# 1차원으로 만든다.

array([2, 3, 4, 5, 6, 7, 8, 9])

# astype

In [69]:
a = np.linspace(0, 100)

In [70]:
a.dtype

dtype('float64')

In [71]:
b = a.astype(str)
b
# a의 type을 변환한다.

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [72]:
np.random.rand()

0.012278814216728495

In [74]:
np.random.rand(2,3)

array([[0.17538397, 0.59774447, 0.38060491],
       [0.79387984, 0.06645807, 0.62410765]])

In [78]:
np.random.randint(1,10, 28).reshape(7, 4)

array([[8, 3, 9, 6],
       [1, 9, 1, 7],
       [3, 2, 5, 2],
       [1, 6, 6, 2],
       [3, 4, 3, 5],
       [1, 8, 6, 1],
       [5, 2, 1, 5]])

In [79]:
np.random.randn(2, 2)

array([[0.11741406, 0.50585464],
       [0.95170291, 1.67829335]])

# 인덱스

In [95]:
a = np.linspace(1, 20, 9)
a

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [96]:
a[0]

1.0

In [97]:
a[1]

3.375

In [98]:
a = a.reshape(3,3)

In [99]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [104]:
a[1][2]
# 일반적인 접근방법

12.875

In [103]:
a[1,2]
# 이방식도 가능하다. 시간단축과 메모리 확보

12.875

In [106]:
a[1:]

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [107]:
a[:3]

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [108]:
a[:2]

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875]])

In [111]:
a[:, :1]
# 전체 행에서 1열 미만의 행까지 가져온다.

array([[ 1.   ],
       [ 8.125],
       [15.25 ]])

In [112]:
b = a.reshape(-1)

In [113]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [114]:
b[1::2]

array([ 3.375,  8.125, 12.875, 17.625])

In [116]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [119]:
a[::2,::2]
# 인덱스의 개념 확장

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [121]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [124]:
b[b>3]
# 조건을 줄 수 있다.

array([ 3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [125]:
b[b>10]

array([10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [129]:
a[1, a[1]>9]
# 해당 행에 대한 조건도 넣을 수 있다.

array([10.5  , 12.875])

In [130]:
np.nan

nan

In [134]:
np.inf
# 이상치 처리

inf

# 벡터 연산

In [136]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [140]:
np.arange(10) + np.arange(50, 60)
# 1:1 로 대응되면 계산이 가능하다.

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])