# 행렬로 푸는 다중회귀

In [ ]:
# numpy 모듈 임포트
import numpy as np 

In [3]:
# X 데이터 생성
# 2 by 2 의 행렬
x_data = np.arange(1,5).reshape(2,2)
x_data

array([[1, 2],
       [3, 4]])

In [4]:
# y 데이터 생성
# 2 by 1 의 행렬
y_data = np.arange(2,6,2).reshape(2,1)
y_data

array([[2],
       [4]])

In [5]:
print(x_data.shape)
print(y_data.shape)

(2, 2)

In [7]:
# x의 전치행렬
# np.transpose()
x_trans = np.transpose(x_data)
x_trans

array([[1, 3],
       [2, 4]])

In [8]:
# x의 전치행렬 * x 데이터
x_trans_product_x_data = np.matmul(x_trans, x_data)
x_trans_product_x_data

array([[10, 14],
       [14, 20]])

In [9]:
# (x의 전치행렬 * x 데이터) 의 역행렬
producted_inverse = np.linalg.inv(xbyx_trans)
producted_inverse

array([[ 5. , -3.5],
       [-3.5,  2.5]])

In [11]:
# B^ = (x의 전치행렬 * x 데이터) 의 역행렬 * x의 전치행렬 * y 데이터
temp = np.matmul(inverse, x_trans)
final = np.matmul(temp, y_data)
final

array([[-3.55271368e-15],
       [ 1.00000000e+00]])

In [12]:
# x * B^ 
np.matmul(x_data, final)

array([[2.],
       [4.]])