# Numpy

In [2]:
import numpy as np
# numpy를 불러옵니다.

In [4]:
a = np.array(range(10))
# a는 numpy array를 생성하고, array는 0부터 시작해서 10개의 범위를 가져옵니다.

In [5]:
a
# 10개의 요소가 있는 array가 생성되었습니다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(a)
# class로 구현됨
# a의 타입은 numpy의 array 입니다.

numpy.ndarray

In [7]:
l1 = [5, 4, 8, 10]
b = np.array(l1)
b
# 리스트 하나가 있습니다. 리스트 이름은 l1으로 설정합니다. 
# l1 은 5, 4, 8, 10을 요소로 가집니다.
# b를 numpy array로 만듭니다. 

array([ 5,  4,  8, 10])

In [8]:
a.dtype

dtype('int32')

In [10]:
b.dtype
# a와 b 모두 정수가 들어가있기 때문에 int가 나타납니다.
# 만약에 실수가 섞여 있으면 전부 float 형으로 바뀝니다.

dtype('int32')

In [11]:
l2 = [1, 2.0, 3, 'a']
l2
# l2 는 정수, 실수, 문자열이 들어있는 리스트입니다.

[1, 2.0, 3, 'a']

In [13]:
np.array(l2)
# 이렇게 문자가 껴있는 경우, 숫자가 문자로 바뀌어서 들어간다.
# 숫자를 문자로 바꾸는 것이 문자를 숫자로 바꾸는 것보다 쉽기 때문입니다.
# 타입 역시 유니코드로 바뀝니다.

array(['1', '2.0', '3', 'a'], dtype='<U32')

In [14]:
l3 = [1, 2.0, 3.0, 5.7]
c = np.array(l3)
c
# l3은 정수와 실수로 구성되어 있는 리스트입니다.

array([1. , 2. , 3. , 5.7])

In [15]:
c.dtype
# 타입을 살펴보면, 정수였던 값 뒤에 .이 붙어 실수형으로 바뀝니다. 타입 역시 float 형으로 나옵니다.

dtype('float64')

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b

array([ 5,  4,  8, 10])

In [18]:
c

array([1. , 2. , 3. , 5.7])

In [19]:
a.shape
# 개수 10개, 한 줄

(10,)

In [20]:
b.shape
# 개수 4개, 한 줄 

(4,)

In [21]:
c.shape
# 개수 4개, 한 줄 

(4,)

# 차원의 개념

In [24]:
l1 = [[1,2], [3,4]]
a = np.array(l1)
a
# l1은 리스트 [1,2], [3,4]를 요소로 가지고 있는 리스트입니다.

array([[1, 2],
       [3, 4]])

In [26]:
a.dtype
# 정수만이 들어있기 때문에 int형이 나타납니다.

dtype('int32')

In [28]:
a.shape
# 2 by 2의 행렬이라고 볼 수 있습니다.

(2, 2)

In [30]:
l2 = [[1,2,3], [3,4]]
b = np.array(l2)
b
# 차원의 개념이 적용되기 위헤서는 행, 열의 숫자가 같아야 합니다.
# 따라서, 행렬로 나타나는 것이 아닌, 리스트를 나타내 줄 것입니다.

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [31]:
range(10)

range(0, 10)

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2, 10, 2)
# range 와 사용이 똑같다.
# 범위를 지정하고, 몇 단계씩 건너 뛸 것인지도 설정할 수 있습니다.

array([2, 4, 6, 8])

# linspace

In [38]:
# ???????????????
np.linspace(10,20, 9)
# 10이상 20"이하"의 구간을 9구간으로 균등하게 잘라서 가져온다.
# default 값은 50

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

# Shape

In [39]:
a = np.arange(2, 10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.shape
# 8개의 요소가 있는 벡터(1행)형

(8,)

In [42]:
b = a.reshape(2, 4)
b
# 2행 4열로 만든다.
# 복사해서 새로 생긴다.

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [44]:
b.shape
# 2행 4열

(2, 4)

# Shape를 바꾸는 다른 방법

In [45]:
a.shape

(8,)

In [46]:
a.shape = (2,4)
a
# 직접 바꾸는 방법
# 2행 4열로, 2 x 4 

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [47]:
a.shape = (-1)
a
# 1차원으로 만든다.

array([2, 3, 4, 5, 6, 7, 8, 9])

##  reshape정리
##### [ 배열 ] . reshape(   ) < 복사해서 바뀐다.
##### [ 배열 ] , shape = (   ) < 직접 배열 자체가 바뀐다.
##### [ 배열 ] , shape = (-1) < 몇행 몇열이던 간에, 무조건 1행 행렬로 바뀐다.


# astype

In [48]:
a = np.linspace(0, 100)

In [49]:
a.dtype

dtype('float64')

In [51]:
a

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [53]:
b = a.astype(str)
b
# a의 type을 변환한다.
# string 형태로 변환이 됩니다.

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [54]:
np.random.rand()

0.4334100251094791

In [58]:
np.random.rand(2,3)
# 2행 3열로 무작위 난수를 생성합니다.
# random.rand 와 random.randint는 사용법이 다르다는 것을 명심해야합니다.

array([[0.50537202, 0.43676037, 0.81169452],
       [0.49140651, 0.82267735, 0.89782939]])

In [13]:
np.random.randint(1, 10, 28).reshape(7, 4)
# 1부터 10미만의 숫자를 28개 생성 

array([[1, 1, 3, 6],
       [8, 9, 5, 4],
       [2, 4, 6, 5],
       [6, 4, 9, 5],
       [9, 6, 4, 7],
       [3, 6, 5, 1],
       [2, 8, 1, 3]])

In [62]:
np.random.randn(2, 2)
# 2행 2열로 평균이 0 표준편차가 1인 정규분포내의 난수 생성

array([[ 0.64366503, -1.12672908],
       [-0.44470389,  0.99121802]])

# 인덱스
## 접근방법

In [121]:
a = np.linspace(1, 20, 9)
a
# 1이상 20이하 까지의 수를 9개로 균등하게 잘라서 가져옵니다.
# 이상 미만이 아닌 양 끝으로 생가갷야합니다.

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [65]:
a[0]
# a의 0번째. 즉 1을 반환할 것입니다.

1.0

In [66]:
a[1]
# 3.375를 반환할 것입니다.

3.375

In [67]:
a = a.reshape(3,3)
# 3행 3열의 모양으로 모양을 바꿉니다.

In [68]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [69]:
a[1][2]
# 일반적인 접근방법
# 1 번째 행의 2 번째 요소를 가져올 것입니다.
# 1번째 행은 [8.125, 10.5, 12.875]이고, 2 번재 요소는 12.875입니다.

12.875

In [70]:
a[1,2]
# 이러한 방식도 가능하다. 시간단축과 메모리 확보

12.875

In [71]:
a[1:]
# 1번째 행부터 끝까지 가져올 것입니다. 

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [72]:
a[:3]
# 모든 행과 열을 가져올 것입니다.

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [73]:
a[:2]
# 2번째 미만의 행까지 가져올 것입니다.

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875]])

In [74]:
a[:, :1]
# 전체 행에서 1열 미만의 열까지 가져온다.

array([[ 1.   ],
       [ 8.125],
       [15.25 ]])

In [75]:
b = a.reshape(-1)
# 벡터형으로 반환합니다. 1차원으로 변경

In [76]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [77]:
b[1::2]
# 1번빼부터 끝까지 2개의 스텝으로 잘라서 가져올 것입니다.
# 3.375, 8.125, 12.875, 17.625

array([ 3.375,  8.125, 12.875, 17.625])

In [78]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [79]:
a[::2,::2]
# 인덱스의 개념 확장
# 행은 처음부터 끝까지 2단계씩 건너뛰면서, 즉 0 번째 행과 2번째 행
# 그 다음,
# 열 역시 처음부터 끝까지 2단계씩 건너 뛰면서 반환 즉 
# 1, 5.75
# 15.25, 20. 반환

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [80]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [82]:
b[b>3]
# 조건을 줄 수 있다.
# 3을 초과하는 숫자들을 반환할 것입니다.

array([ 3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [83]:
b[b>10]

array([10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [85]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [87]:
a[1, a[1]>9]
# 해당 행에 대한 조건도 넣을 수 있다.
# 첫번째 행에서 9보다 큰 수만을 반환합니다.

array([10.5  , 12.875])

In [88]:
np.nan

nan

In [89]:
np.inf
# 이상치 처리

inf

# 벡터 연산

In [90]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a + 1
# 모든 요소에 1이 더해집니다.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
np.arange(10) + np.arange(50, 60)
# 1:1 로 대응되면 계산이 가능하다.

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [93]:
# 소수 형태의 문자열
data1 = ['1.5', '.62', '3.14', '3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

## float 형

In [94]:
float_arr = str_arr.astype(float) # or   float_arr = str_arr.astype('f')
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [95]:
float_arr.dtype

dtype('float64')

## int 형

In [96]:
int_arr = float_arr.astype(int)
int_arr

array([1, 0, 3, 3])

In [97]:
int_arr.dtype

dtype('int32')

## unicode형

In [98]:
# unicode = string
unicode_arr = int_arr.astype(str)
unicode_arr

array(['1', '0', '3', '3'], dtype='<U11')

In [99]:
unicode_arr.dtype

dtype('<U11')

## 복소수형(complex)

In [100]:
# j=i
complex_arr = float_arr.astype(complex)
complex_arr

array([1.5     +0.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

In [101]:
complex_arr.dtype

dtype('complex128')

In [102]:
complex_arr[0] = 2-2j # 복소수 추가.

In [103]:
complex_arr

array([2.      -2.j, 0.62    +0.j, 3.14    +0.j, 3.141592+0.j])

# 난수 배열의 생성

# rand 함수

In [105]:
rand_float = np.random.rand()
rand_float
# 난수 하나를 생성합니다.

0.7934623297419205

In [106]:
#size 지정
rand_float_arr1 = np.random.rand(4)
# 난수를 4개 생성합니다.
rand_float_arr1

array([0.90697919, 0.84167379, 0.04631167, 0.6575055 ])

In [108]:
rand_float_arr1.shape
# 4개의 요소를 가진 1행(벡터형)

(4,)

## rand 함수 다차원

In [109]:
rand_float_arr2 = np.random.rand(3,3)
rand_float_arr2
# 3행 3열의 다차원으로 생성합니다.

array([[0.68361631, 0.12015902, 0.64195971],
       [0.24476145, 0.29166592, 0.88465063],
       [0.83254802, 0.1423712 , 0.92386841]])

In [110]:
rand_float_arr2.shape
# 3행 3열

(3, 3)

In [112]:
rand_float_arr3 = np.random.rand(3,3,5)
# 난수를 3개 생성합니다, 하지만, 뒤에 조건이 추가됩니다.
# 3개를 생성합니다. > 3행 5열의 
rand_float_arr3

array([[[0.64414366, 0.22662614, 0.08485764, 0.08318163, 0.91248319],
        [0.88855858, 0.40451711, 0.97002179, 0.20328975, 0.54587806],
        [0.91896965, 0.795415  , 0.58030305, 0.60446087, 0.57438791]],

       [[0.77908663, 0.33402099, 0.33163665, 0.97723484, 0.61089097],
        [0.03796679, 0.410249  , 0.6555771 , 0.95382947, 0.28755991],
        [0.15398642, 0.61361847, 0.67418403, 0.07324811, 0.36105563]],

       [[0.86412077, 0.25887383, 0.92077867, 0.79693351, 0.55357929],
        [0.45718317, 0.72014628, 0.82326531, 0.49126467, 0.6774951 ],
        [0.0633841 , 0.20287488, 0.67988406, 0.79144046, 0.98236101]]])

In [113]:
rand_float_arr3.shape

(3, 3, 5)

## 정수 난수를 생성하는 -randint

In [114]:
# 0~100
rand_int = np.random.randint(100)
rand_int
# np.random.randint 함수는 정수난수를 생성합니다.
# 괄호 안에 넣는 숫자는 0부터 100까지를 의미합니다.

31

In [116]:
# 0~100 까지 size만큼
rand_int_arr1 = np.random.randint(100, size=(3,4))
rand_int_arr1
# 0부터 100사이의 난수들 중 3행 4열의 난수를 만듭니다.

array([[85, 25, 51, 45],
       [55, 67, 85, 15],
       [ 8, 85,  4, 60]])

In [117]:
rand_int_arr1.shape

(3, 4)

In [118]:
# 80이상 100미만의 정수 중에서 3,3,3, 형태로 배열을 난수로 생성한다.
rand_int_arr2 = np.random.randint(80, 100, size=(3,3,3))
rand_int_arr2

array([[[98, 94, 95],
        [81, 86, 99],
        [99, 88, 98]],

       [[89, 92, 89],
        [88, 93, 93],
        [84, 93, 96]],

       [[83, 98, 89],
        [95, 90, 98],
        [88, 96, 80]]])

In [119]:
rand_int_arr2.shape

(3, 3, 3)

## 정규분포 샘플링 np.random.randn

In [120]:
# 5,10의 표준 정규분포에서 샘플링
# 평균이 0 표준편차가 1
rand_n_arr = np.random.randn(5,10)
rand_n_arr

array([[ 0.2106904 ,  2.02432682,  0.93040805,  1.01605164,  0.28476142,
        -0.40663194,  1.87300216, -0.99773071, -1.22725657, -0.33689467],
       [-0.36861111, -1.11427379,  1.39868754, -2.55330287,  1.15753266,
        -0.11672998,  0.40064513, -0.22372549, -0.56358858, -0.56085747],
       [-0.29215694, -0.78180234, -0.5553207 , -0.24383088, -0.683645  ,
        -0.25810416,  1.09878055,  0.24098643, -1.09969376,  0.24097525],
       [-0.8693256 , -0.91632264, -0.73438607,  0.66974019, -0.97460126,
         0.60645392, -1.0460895 ,  0.36512322, -1.41715296, -0.2106105 ],
       [ 0.29426353, -0.05022152,  0.49279975, -0.58413126,  0.30825304,
         1.87098877, -1.02947413, -2.08211624, -1.71986466, -2.56627239]])

# 배열의 인덱싱과 슬라이싱

In [14]:
arr1 = np.arange(0, 60, 10)
arr1
# 0부터 60미만의 수를 10씩 잘라서 가져옵니다. 

array([ 0, 10, 20, 30, 40, 50])

In [15]:
# 리스트와 같음
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
10
50


In [16]:
arr1[:4]
# 0이상 3미만까지 

array([ 0, 10, 20, 30])

In [17]:
arr1[3:]

array([30, 40, 50])

In [18]:
arr1[::2]
# 전체를 가져오면서 스텝을 2개씩 

array([ 0, 20, 40])

## 배열 수정하기

In [19]:
arr1[1] = 100
arr1
# 리스트와 똑같다.

array([  0, 100,  20,  30,  40,  50])

## 배열 부분 인덱싱

In [20]:
arr1[[1,4]]
# 1 번째 데이터와 4 번째 데이터를 가져온다. 

array([100,  40])

In [21]:
arr1[[1, 3, 4]]
# 1 번째 데이터와 3, 4번째 데이터를 가져온다.

array([100,  30,  40])

## 2차원 배열 인덱싱 슬라이싱

In [22]:
# 2차원 배열 만들기
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# row 가져오기
arr1[1]

array([3, 4, 5])

In [24]:
# row 가져온 후 column 지정
arr1[1][1]

4

In [25]:
# 값 변경하기
# row 접근하고, cloumn 접근한 뒤, = 값으로 지정하면 값이 바뀌게된다.
arr1[1][1] = 30
arr1

array([[ 0,  1,  2],
       [ 3, 30,  5],
       [ 6,  7,  8]])

In [ ]:
# row, cloumn 을 한번에 접근하기
arr1[0, 2]

In [ ]:
arr1[0, 2] = 10

In [ ]:
# 행과 열을 가져온다.
# 위에와 주의해야한다.
arr1[[0,2]]
# 위에 있는 배열을 요소 자체로 생각하면, 0번째와 2번째를 가져오는 것이기 때문에, 0110 과 678을 가져오게된다.

In [ ]:
arr1[[0,2], [0,1]]

In [ ]:
# row단위로 변경
arr1[2] = [3,3,3] 
arr1

In [ ]:
arr1[1:,1:]
# ??? why?

In [ ]:
# slicing 대입
arr1[1:, 1:] = np.array([[1,2],[3,4]])
arr1

## 조건으로 인덱스 슬라이싱

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

In [ ]:
arr1[arr1>50]
# 50보다 큰 것만 가져온다.

In [ ]:
arr2 = np.arange(10, 170, 10).reshape(4, 4)
arr2

In [ ]:
arr2[arr2%4 == 0]
# 벡터의 방식으로 나온다.따라서 reshape 를 해주어야한다.

In [ ]:
arr2[:-1:2, ::2]

# NaN (not a number) & Inf(Infinity)
### 수치가 없는 값. 누락값

In [26]:
import numpy as np

In [27]:
np.nan

arr1 = np.array([1,2,3, np.nan, np.inf])
arr1

array([ 1.,  2.,  3., nan, inf])

In [28]:
arr1.dtype

dtype('float64')

## 특별한 형태의 배열 생성

In [29]:
# 모두 0인 배열
arr_zero_n = np.zeros(9)
arr_zero_n

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 모두 0인 3,3 배열
arr_zero_mxn = np.zeros((3,3))
arr_zero_mxn

In [ ]:
# 모두 1인 배열
arr_one_n = np.ones(9)
arr_one_n

In [ ]:
# 모두 1인 3,3 배열
arr_one_mxn = np.ones((3,3))
arr_one_mxn

In [30]:
arr_two_mxn = np.twos((3,3))
arr_two_mxn

AttributeError: module 'numpy' has no attribute 'twos'

In [31]:
# 단위 행렬 
arr_I = np.eye(5)
arr_I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 단위 행렬 다른 방법
arr_I2 = np.identity(5)
arr_I2

# 배열의 연산

In [32]:
# shape이 같아야함
arr1 = np.arange(1.0,7)
arr2 = np.arange(10.0,70,10)

# repr은 클래스에서 __repr__을 호출하는 함수
print('arr1: %s \t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([1., 2., 3., 4., 5., 6.]) 	 shape:(6,)
arr2: array([10., 20., 30., 40., 50., 60.]) 	 shape:(6,)


In [33]:
arr1 + 100

array([101., 102., 103., 104., 105., 106.])

In [34]:
arr1 + arr2

array([11., 22., 33., 44., 55., 66.])

In [35]:
arr1 - 5

array([-4., -3., -2., -1.,  0.,  1.])

In [36]:
arr1 - arr2

array([ -9., -18., -27., -36., -45., -54.])

In [37]:
arr1 * 5

array([ 5., 10., 15., 20., 25., 30.])

In [38]:
arr1 * arr2

array([ 10.,  40.,  90., 160., 250., 360.])

In [39]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [40]:
arr1 / arr2

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [41]:
arr1 ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [42]:
# 배열의 복합연산 역시 가능
(arr1 + 100) / arr2

array([10.1       ,  5.1       ,  3.43333333,  2.6       ,  2.1       ,
        1.76666667])

### 배열의 비교연산
#### boolean 형으로 나온다.

In [43]:
arr2 > 20 # (조건으로 인덱싱)

array([False, False,  True,  True,  True,  True])

In [44]:
arr2[arr2>20]

array([30., 40., 50., 60.])

In [45]:
arr2[[False, False,  True,  True,  True,  True]]
# 벡터 연산을 통해서 가져오는 것이다.

array([30., 40., 50., 60.])

# 다차원 배열에서의 연산

In [49]:
arr1 = np.arange(1,9).reshape(2,4) 

arr2 = np.arange(10,90,10).reshape(2,4)

print('arr1: %s \t\t shape:%s' % (repr(arr1), arr1.shape))
print('arr2: %s \t shape:%s' % (repr(arr2), arr2.shape))

arr1: array([[1, 2, 3, 4],
       [5, 6, 7, 8]]) 		 shape:(2, 4)
arr2: array([[10, 20, 30, 40],
       [50, 60, 70, 80]]) 	 shape:(2, 4)


In [50]:
# 요소간 곱셈
arr1*arr2

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

# 통계를 위한 연산
## 유용한 연산

# 합계 sum / 평균 mean

In [ ]:
arr1 = np.arange(1, 11)
arr1

In [ ]:
arr1.sum(), arr1.mean()

## 표준편차, 분산

In [ ]:
# std = sqrt(var)
arr1.std(), arr1.var()

## min - 최소값 / max - 최대값

In [ ]:
arr1.min(), arr1.max()

## cumsum - 누적합 / cumprod - 누적곱

In [ ]:
arr1.cumsum(), arr1.cumprod()

# 행렬연산

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 0, -1).reshape(3, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

# 1. A.dot(B)
# 2. np.matnul(A,B)
# 3. A @ B
# 곱하는 순서 역시 중요하다. 3.번을 쓰는것을 추천
# 앞쪽의 '열의 수' = 뒤쪽의 '행의 수' 가 같아야 한다.

## 행렬 곱

In [ ]:
# 지양
A.dot(B)

In [ ]:
np.dot(B,A)

In [ ]:
A @ B

In [ ]:
B @ A

## 전치행렬

In [ ]:
A

In [ ]:
A.transpose()

In [ ]:
A.T
# 가장 자주 쓴다.

In [ ]:
np.transpose(A)

## 단위행렬

In [ ]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(4, 0, -1).reshape(2, 2)

print("A: %s" % repr(A))
print("B: %s" % repr(B))

In [ ]:
I = np.eye(2)
I

In [ ]:
A @ I

In [ ]:
B @ I

## 역행렬

In [ ]:
A

In [ ]:
B

In [ ]:
Ai = np.linalg.inv(A)
Ai

In [ ]:
A @ Ai
# 단위행렬이 나와야 한다.
# 오차가 생길 수 있지만, 너무 작은 수라서 0이라고보아도 무방하다.

In [ ]:
Bi = np.linalg.inv(B)
Bi

In [ ]:
B @ Bi

## 행렬식

In [ ]:
np.linalg.det(A)

In [ ]:
np.linalg.det(B)

In [ ]:
dir(np)
# 행렬에서 사용할 수 있는 식들 확인