## 2.2 Sklearn

- 데이터 불러오기
- 2.2.1 싸이킷-런 데이터 분리
- 2.2.2 싸이킷-런 지도 학습
- 2.2.3 싸이킷-런 비지도 학습
- 2.2.4 싸이킷-런 특징 추출

In [1]:
import sklearn 
sklearn.__version__

'0.20.3'

## 데이터 불러오기

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris_dataset = load_iris()
print("Iris_dataset key: {}".format(iris_dataset.keys()))

Iris_dataset key: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
print(iris_dataset['data'])
print("Shape of data: {}". format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(iris_dataset['feature_names']) # 4개의 feature가 존재

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


## 2.2.1 싸이킷-런 데이터 분리

In [8]:
target = iris_dataset['target']

from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    target,
                                                                   test_size = 0.25,
                                                                   random_state=42)

In [9]:
print("shape of train_input: {}".format(train_input.shape))
print("shape of test_input: {}".format(test_input.shape))
print("shape of train_label: {}".format(train_label.shape))
print("shape of test_label: {}".format(test_label.shape))

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


## 2.2.2 싸이킷-런 지도학습

- 어떻게 K를 결정할 것인가?
    - K는 hyperparameter
    - 연구에 따르면 모든 종류의 데이터 세트에 적합한 최적의 이웃 수가 없음
    - K가 적으면 노이즈가 결과에 더 큰 영향을 미치며, K가 많으면 계산 비용이 많이 듬
    
- 장점
    - 분류 알고리즘에 비해 훨씬 빠르다
    - 일반화를 위한 모델을 교육할 필요가 없기 때문
    
- 단점
    - KNN의 테스트 단계는 시간과 메모리 측면에서 더 느리고 비용이 많이 듦
    - 예측을 위해 전체 학습 데이터 세트를 저장하려면 큰 메모리가 필요
    - KNN은 두 데이터 포인트 사이의 유클리드 거리를 사용하여 가장 가까운 이웃을 찾기 때문에 데이터 스케일링이 필요
    - 여기서, DATA SCALEING이란?
    
    - KNN은 또한 큰 차원의 데이터에는 적합하지 않습니다. (PCA의 필요성)
    
- 성능을 높이기 위해서는
    - 동일한 규모로 데이터를 정규화(정규화 범위는 0과 1 사이)
    - KNN은 큰 차원의 데이터에는 적합학 ㅣ않음 -> 차원을 줄여 성능향상
  

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [12]:
# fit을 한다는 것, train_input과 train_label을 적용한다. 
knn.fit(train_input, train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [16]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [17]:
knn.predict(new_input)

array([1])

In [19]:
predict_label = knn.predict(test_input)
print(predict_label)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [22]:
print('test accuracy: {: .2f}'.format(np.mean(predict_label == test_label)))

test accuracy:  1.00


In [24]:
# Assigning features and label variables
# Frist Feature
weather =['Sunny','Sunny','Overcast','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label of target variable
play = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

from sklearn import preprocessing
# creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers
weather_encoded = le.fit_transform(weather)
print(weather_encoded)

[2 2 0 1 1 0 2 2 1 2 0 0 1]


In [26]:
# converting string labels into numbers
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)

In [29]:
# combinig weather and temp into single list of tuples
features = list(zip(weather_encoded,temp_encoded))
print(features)

[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (0, 0), (2, 0), (2, 2), (1, 0), (2, 2), (0, 2), (0, 2), (1, 1)]


In [34]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 3)

# Train the model using the training sets
model.fit(features,label)

# Predict Cutput
predicted = model.predict([[0,2]]) # 0: Overcast, 2: Mild
print(predicted)

ValueError: Found input variables with inconsistent numbers of samples: [13, 14]

## 2.2.3 싸이킷 런 비지도 학습

K를 정하는 방법
   - 1. Rule of Thumb  
   가장 간단한 방법.  
   데이터의 수가 n이라 할때, 필요한 클러스터의 수는 다음과 같이 계산
   K = SQRT(n/2)  
      
   - 2. Elbow Method
   클러스터의 수를 순차적으로 늘려가면서 결과를 모니터링. 하나의 클러스터를 추가했을 때, 이전보다 훨씬 더 나은 결과를 제공하지 않는다면, 이전의 클러스터 수를 사용한다.  
   그러나, 항상 결과가 동일하지 않음. 군집화를 진행할때마다 바뀌는데, 특히 초기값에 영향을 많이 받는다.
    
   - 3. 그러나, 가장 좋은 방법은 데이터에 대해서 잘 아는 사람이 K의 수를 정해주는 것이 가장 좋다.
    

In [36]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters = 3)

k_means.fit(train_input)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [39]:
k_means.labels_

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 1,
       1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0,
       2, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0,
       2, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 2])

In [41]:
print("0 cluster: ", train_label[k_means.labels_ == 0])
print("1 cluster: ", train_label[k_means.labels_ == 1])
print("2 cluster: ", train_label[k_means.labels_ == 2])

0 cluster:  [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
1 cluster:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 cluster:  [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


In [42]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [43]:
prediction = k_means.predict(new_input)
print(prediction)

[0]


In [44]:
predict_cluster = k_means.predict(test_input)
print(predict_cluster)

[0 1 2 0 0 1 0 2 0 0 2 1 1 1 1 0 2 0 0 2 1 0 1 2 2 2 2 2 1 1 1 1 0 1 1 0 0
 1]


In [53]:
np_arr = np.array(predict_cluster)
print('old: ', np_arr)
# 위에서 random으로 클러스터링의 순서가 바뀌었기 때문에, 이를 다시 맞춰준다. 
np_arr[np_arr == 0], np_arr[np_arr == 1], np_arr[np_arr ==2] = 3, 4, 5
print('new: ', np_arr)
np_arr[np_arr == 3] = 1
np_arr[np_arr == 4] = 0
np_arr[np_arr == 5] = 2
predict_label = np_arr.tolist()
print(predict_label)

old:  [0 1 2 0 0 1 0 2 0 0 2 1 1 1 1 0 2 0 0 2 1 0 1 2 2 2 2 2 1 1 1 1 0 1 1 0 0
 1]
new:  [3 4 5 3 3 4 3 5 3 3 5 4 4 4 4 3 5 3 3 5 4 3 4 5 5 5 5 5 4 4 4 4 3 4 4 3 3
 4]
[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]


In [56]:
print('test_accuracy {: .2f}'.format(np.mean(predict_label == test_label)))
# f는 flot형태로 출력하겠다는 의미 
# 앞에 2는 소숫점 절사 


test_accuracy  0.95
