# LinearRegression_model_comprehension

In [162]:
from sklearn.datasets import make_regression # 가상의 회귀분석 데이터 생성
from sklearn.linear_model import LinearRegression # LinearRegression 모델 객체
from sklearn.model_selection import train_test_split # 나누는 함수 
import numpy as np

In [175]:
X, y = make_regression(n_samples=1000, n_features=1, bias=10, noise=10)
print('input_feature:\n {}\nTarget_value: \n{} '.format(X[:5], y[:5]))

# sample = 전체 데이터 개수
# features = 전체 변수의 개수 
# bias = 편향. 절편
# noise = 소음. 이상치..? (확인필요)

input_feature:
 [[-0.443936  ]
 [-0.45172434]
 [ 1.83532421]
 [-0.48350458]
 [ 1.41465091]]
Target_value: 
[-17.7208862  -15.0092598   71.72527893  -8.62996975  83.63351981] 


In [176]:
print(type(X), type(y)) # numpy의 배열 

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [177]:
%matplotlib inline 
# mat + plot + libreary 라이브러리 
import matplotlib.pyplot as plt

plt.scatter(X[:, 2], y) # 산포도 # 전체행렬에서 1열 데이터를 찝는다.
plt.show()

IndexError: index 2 is out of bounds for axis 1 with size 1

In [178]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
# train_test_split을 통해서 사이즈 나누기
# shuffle: 섞기 

In [179]:
X_train # 8000개 (위에서 8:2로 나눔)

array([[-9.86231654e-01],
       [ 5.85669701e-01],
       [ 9.75878581e-01],
       [-4.73725406e-01],
       [-2.03406395e-01],
       [-3.14623056e-01],
       [ 5.64194629e-01],
       [-1.70092780e-01],
       [ 9.90215537e-03],
       [-3.39884461e-01],
       [ 6.87989029e-01],
       [-9.92027108e-01],
       [ 1.02394254e+00],
       [ 1.08905567e+00],
       [ 1.58524790e+00],
       [ 4.10849454e-01],
       [-2.47988071e+00],
       [-6.11870464e-01],
       [-2.20628165e+00],
       [-1.61504434e+00],
       [ 1.41465091e+00],
       [ 1.70768982e+00],
       [-1.45566323e+00],
       [-4.22217389e-01],
       [-1.85487672e+00],
       [ 7.99628359e-01],
       [-1.43479477e+00],
       [ 3.29122234e-02],
       [ 6.00919562e-01],
       [ 1.27095731e-03],
       [ 7.01925998e-01],
       [ 7.94788418e-01],
       [-1.19196177e+00],
       [-8.06840616e-01],
       [ 1.88829153e+00],
       [ 2.40005070e-01],
       [ 1.11487938e+00],
       [-8.78256154e-01],
       [ 5.3

In [180]:
# Linear Regression 클래스 객체 생성 
model = LinearRegression() # fit_intercept = 상수항 유무 결정 

# fit 메서드로 모형 추정 (오그멘테이션은 자동으로 수행) 
model_lr = model.fit(X_train, y_train) # lr? : linear regression

print('weight: ', model_lr.coef_) # 기울기 
print('bias: ', model_lr.intercept_) # 절편

# weight는 10개가 나오는데, 위에서 feature를 10개로 설정했기 때문이다.

weight:  [48.69080598]
bias:  9.636749256924682


#### feature 1000, n_samples 1000 으로 설정하면 과적합 overfitting 발생 
#### feature 수가 너무 높으면 제대로 작동하지 않는다. 즉 PCA, 주성분 분석을 함으로써 feature수를 줄여주어야한다.

In [181]:
model.score(X_train, y_train) # 100을 곱해서 퍼센트로 환산. noise를 올릴수록 정확도가 낮아진다. 

0.9656115023758622

In [182]:
model.score(X_test, y_test) # 100을 곱해서 퍼센트로 환산. noise를 올릴수록 정확도가 낮아진다. 

0.9573811188747748

In [183]:
model.predict(np.array([1,2]).reshape(2,1))

# fir과 predict의 차이 

array([ 58.32755523, 107.01836121])

# RidgeRegression_model_comprehension

In [188]:
from sklearn.datasets import make_regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

##### 데이터생성

In [189]:
X, y = make_regression(n_samples=10000, n_features=1000, bias=10, noise=100)
# 일부러 과적합이 발생할 것으로 예상되는 모델을 생성 

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True)

In [190]:
# Linear Regression 클래스 객체 생성
model = Ridge(alpha=0.1) 
# fit 메서드로 모형 추정 (오그멘테이션은 자동으로 수행)
model_lr = model.fit(X_train, y_train)

print('weight: ', model_lr.coef_)
print('bias: ', model_lr.intercept_)

weight:  [ 1.62753731e+00 -8.29207504e-01  9.19790938e-01  2.70968680e+00
 -7.22106312e-01 -1.83816044e+00 -9.13496943e-01 -2.60692077e+00
 -7.25828849e-01  1.55261207e-01 -2.00592897e+00 -3.26237702e-01
  5.07776539e-01 -8.77600931e-01 -5.90012140e-01 -1.60809273e+00
 -2.52304299e-01  1.32607361e+00  5.43612060e-01 -3.16616553e+00
  1.13670155e+00  5.17862008e-01  1.54059437e+00  1.16906375e+00
 -6.46860771e-02 -3.98420886e-01  4.14999595e-01 -2.78282361e+00
  1.46360005e+00 -1.86321706e+00 -2.37457137e-01 -2.02434974e-01
 -3.44880190e-01 -1.55179523e+00  5.18363094e-01 -1.45198906e+00
 -4.60920652e-01  1.87497145e+00 -8.28530034e-01 -2.03241993e+00
 -1.99633288e-01  2.09387225e+00 -2.82818195e+00  1.70218075e+00
 -3.64649156e-01  1.86745428e+00 -3.78644198e-01  1.60570168e+00
 -1.81763155e+00 -9.50025293e-01  2.24510993e+00 -2.78310010e+00
  2.17569152e+00 -2.49834117e-01  5.11895875e-01 -9.90999746e-01
 -7.60666156e-01  2.20900564e+00 -1.81478273e+00 -9.75333269e-01
  1.37632555e+00

In [191]:
model.score(X_train, y_train)

0.8724001720593242

In [193]:
model.score(X_test, y_test) # Ridge는 정확도는 낮지만, test와 score의 차이가 작다.

0.8271019039018053

# LassoRegression_model_comprehension

In [194]:
from sklearn.datasets import make_regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split

In [204]:
X, y = make_regression(n_samples=10000, n_features=100, bias=10, noise=20)

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [208]:
# Linear Regression 클래스 객체 생성
model = Lasso() # fit_intercept = 상수항 유무 결정

# fit 메서드로 모형 추정 (오그멘테이션은 자동으로 수행)
model_lr = model.fit(X_train, y_train)

print('weight: ', model_lr.coef_) # Lasso 의 경우에는 0이 된 값들이 많은 것을 확인할 수 있다. 
print('bias: ', model_lr.intercept_)

weight:  [13.54275944 52.52833137  0.          0.         -0.          0.
 -0.          0.          0.          0.         21.44094777  0.
  0.          0.          0.         -0.          0.         -0.
 -0.         -0.          0.         -0.         -0.         -0.
  0.          0.         -0.          0.         -0.          0.
  0.         62.37886956  0.          0.         -0.          0.
 -0.          0.          0.          0.          0.         -0.
 -0.         -0.         -0.         -0.          0.          0.
  0.          0.         -0.         -0.          0.         -0.
  0.         -0.         69.86406181  0.          8.64715999 -0.
  0.         -0.         -0.          0.         -0.         -0.
  0.         -0.          0.          0.         -0.          0.
  0.          0.         -0.         10.52216164 65.83752095 -0.
 -0.         -0.         -0.          0.          0.         -0.
  0.         22.71559317  0.         -0.         -0.          0.
 38.40372673  0.

In [209]:
model.score(X_train, y_train)

0.9791048298600594

In [210]:
model.score(X_test, y_test)

0.9783481383959716